---
title: "Lab 03 - Degree Centrality - INSTRUCTIONS"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set ( echo = TRUE )
```

# Introduction

The purpose of this lab is to familiarize yourself with calculating degree centrality and degree centralization scores for undirected and directed networks in *R*. Please review the [Degree Centrality](https://jacobtnyoung.github.io/snaca-textbook/snaca-centrality-degree.html) chapter of the [Social Network Analysis for Crime Analysts](https://jacobtnyoung.github.io/snaca-textbook/index.html) textbook and the [Degree Centrality and Centralization](https://jacobtnyoung.github.io/snaca-r/snaca-r-degree-centrality.html) tutorial in the [Social Network Analysis for Crime Analysts using R](https://jacobtnyoung.github.io/snaca-r/index.html) textbook prior to beginning this lab.    

In Parts I and II of this lab, we will use two new networks (described below). In Part III, you will use the two networks you created from [Lab 1](../labs/lab-01-instructions.html) and [Lab 2](../labs/lab-02-instructions.html). Part IV, gives instructions for your *Analytical Briefing*.

::: {.callout-note title="Network and Matrix Objects"}
*Note* in this lab you will work with objects from the `SNACpack` package. All networks in the `SNACpack` package are of class `network`. This means that to use functions for objects of class `matrix` (such as `dim()` or `sum()`), you need to first coerce the object to a `matrix` object using `as.matrix`. For example: `my_matrix <- as.matrix( my_network )`. Keep this in mind as you work through this lab.
:::

<br>

## Part I: Working with an Undirected Network

For this part of the lab, you will use data from [Margaret R. Weeks, Scott Clair, Stephen P. Borgatti, Kim Radda & Jean J. Schensul's analysis](https://link.springer.com/article/10.1023/A:1015457400897) of drug users in Hartford, Connecticut. The data were collected as part of a study examining HIV risk in high-risk drug-use settings. Nodes represent individuals, and ties represent social and drug-use relationships identified through outreach and referral-based sampling. This *undirected* network captures connections among people who gathered at locations where injecting drugs or smoking crack cocaine occurred. Researchers used the network to study how social structure influences risk behaviors and how prevention information might spread through peer relationships. 

This network is available in `SNACpack` as an object of class `network` and is labeled `drug_net`. To review documentation on the network, use this command: `?drug_net`.

For the `drug_net` network, do the following:  

  1. Plot the network using this command: `gplot( drug_net )`.
  1. Describe how you would modify this plot to improve interpretability for a lay audience. Suggest at least <u>three changes</u> and explain why they matter. Be sure to pay attention to the type of network it is and how best to represent the information in the network.
  1. Implement the proposed changes using `gplot()` and describe how each change affects how we see the network.
  1. Calculate the degree centrality score for each actor using the `rowSums()` function. 
  1. Plot the network using the `gplot()` function where nodes are sized by their degree centrality score (be sure to use the `vertex_rescale()` function to aid with correct sizing).
  1. Calculate the standardized degree centrality score using the equation from the readings for this week. 
  1. Calculate the mean degree centrality score.
  1. Calculate the graph centralization score for degree centrality using the `centralization()` function in the `sna` package. 
  
<br>

## Part II: Working with a Directed Network

For this part of the lab, you will use data from [Mangia Natarajan's study](https://link.springer.com/article/10.1007/s10940-006-9007-x) of a large heroin trafficking organization in New York City. The network is directed, with binary ties of communication between individuals collected from police wiretaps of telephone conversations. 

This network is available in `SNACpack` and is called `heroin_dealing_net`. To review documentation on the network, use this command: `?heroin_dealing_net`. 

For the `heroin_dealing_net` network, do the following:  

  1. Plot the network using this command: `gplot( heroin_dealing_net )`.
  1. Describe how you would modify this plot to improve interpretability for a lay audience. Suggest at least <u>three changes</u> and explain why they matter. Be sure to pay attention to the type of network it is and how best to represent the information in the network.
  1. Implement the proposed changes using `gplot()` and describe how each change affects how we see the network.
  1. Calculate the indegree and outdegree centrality scores for each actor using the `rowSums()` and `colSums()` functions. 
  1. Plot the network using the `gplot()` function where nodes are sized by their <u>indegree</u> centrality score (be sure to use the `vertex_rescale()` function to aid with correct sizing).
  1. Plot the network using the `gplot()` function where nodes are sized by their <u>outdegree</u> centrality score (be sure to use the `vertex_rescale()` function to aid with correct sizing).
  1. Calculate the standardized indegree and outdegree centrality scores using the equation from the readings for this week. 
  1. Calculate the mean indegree and outdegree centrality scores.
  1. Calculate the graph centralization scores for indegree and outdegree centrality using the `centralization()` function in the `sna` package. 

<br>

## Part III: Your Networks

Pick **one** of the networks you created in [Lab 1](../labs/lab-01-instructions.html) and [Lab 2](../labs/lab-02-instructions.html), and do the following:

  * If the network is *undirected*, repeat the steps in Part I.  
  
  * If the network is *directed*, repeat the steps in Part II.

<br>

## Part IV: Analytical Briefing

Pretend you are presenting your analysis for **Part II** to a supervisor or investigative team. Your goal is not simply to report numerical results, but to explain what the results reveal about the structure of the `heroin_dealing_net` network and why the results matter. 

Your briefing should address the following topics:

  * Prediction
    * What types of actors would you expect to have high indegree centrality scores and high outdegree centrality scores?
    * How might an actor with high indegree and low outdegree differ from an actor with high scores on both measures?
    * For *indegree*, what would a completely centralized network mean in this setting? What about a completely decentralized network? What about for *outdegree*?

  * Degree Centrality
    * Discuss the actors with the highest indegree and outdegree centrality scores and explain what their positions suggests about their role(s) in the network. Consider what the ties represent when developing your explanation.

  * Centralization
    * Interpret the indegree and outdegree graph centralization scores.
    * What do the indegree and outdegree centralization scores reveal about this network?
    * Are the indegree and outdegree centralization scores similar or different? What does this tell us about the overall structure of the network? Use both the numerical scores and the visualizations to support your conclusions.

  * Implications
    * Assume you are an analyst assigned to investigate heroin trafficking. Based on your analysis: What investigative or intervention strategy would you recommend? Which actors or positions in the network would you prioritize? How did your degree centrality and centralization findings inform this recommendation?

<br>

____

<br>

# How to Submit

Download the [template for this lab](../labs/templates/lab-03-LastName.zip?raw=true) prior to beginning the lab. 

<br>

### Knitting to HTML

When you have completed your assignment, click the "Knit" button to render your `.RMD` file into a `.HTML` report.

<br>

### Special Instructions

Upload your `.RMD`, `.HTML`, and `.MP4` files to the appropriate link for this assignment on the Canvas page for this course.

<br>

### Before You Submit

Remember to ensure the following before submitting your assignment.

  * Name your files using this format: **Lab-##-LastName.rmd**, **Lab-##-LastName.html**, **Lab-##-LastName.mp4**
  * Show both the solution for your code and write out your answers in the body text 
  * Verify that both files open correctly and that your video includes clear audio narration

See [Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml) for examples of common conventions.

<br>
<br>

### Common Knitting Issues

`.RMD` files are knit into `.HTML` and other formats procedural, or line-by-line.

* An error in code when knitting will halt the process; error messages will tell you the specific line with the error
* Certain functions, like `install.packages()` or `setwd()`, are bound to cause errors in knitting 
* Altering a dataset or variable in one chunk will affect its use in all later chunks
* If an object is "not found", make sure it was created or loaded with `library()` in a previous chunk

**If All Else Fails:** If you cannot determine and fix the errors in a code chunk that's preventing you from knitting your document, add `eval = FALSE` inside the brackets of `{r}` at the beginning of a chunk to ensure that R does not attempt to evaluate it, that is: `{r eval = FALSE}`. This will prevent an erroneous chunk of code from halting the knitting process.  