---
title: "Lab 05 - Bipartite Graphs and Two-Mode Networks - INSTRUCTIONS"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE )
```

----

# Introduction

The purpose of this lab is to familiarize yourself with bipartite graphs and two-mode networks in *R*. Prior to beginning this lab, please review the [Bipartite Graphs/Two-Mode Networks](https://jacobtnyoung.github.io/snaca-textbook/snaca-bipartite.html) chapter of the [Social Network Analysis for Crime Analysts](https://jacobtnyoung.github.io/snaca-textbook/index.html) textbook, as well as the [Bipartite Graphs and Two-Mode Networks](https://jacobtnyoung.github.io/snaca-r/snaca-r-bipartite.html) tutorial in the [Social Network Analysis for Crime Analysts using R](https://jacobtnyoung.github.io/snaca-r/index.html) textbook.

In Parts I and II of this lab, we will use two new networks (described below). 
In Part III, you will create your own bipartite network. Part IV, gives instructions for your *Analytical Briefing*.

::: {.callout-note title="Network and Matrix Objects"}
*Note* that the objects, and all networks in the `SNACpack` package, are of class `network`. This means that to use functions for objects of class `matrix` (such as `dim()` or `sum()`), you need to first coerce the object to a `matrix` object using `as.matrix`. For example: `my_matrix <- as.matrix( my_network )`.
:::

<br>

## Part I: A Terrorism Network

For this part of the lab, you will use a network analyzed by [Victor Asal and R. Karl Rethemeyer' study](https://www.journals.uchicago.edu/doi/10.1017/S0022381608080419) of terrorist organizations. The network is two-mode and composed of 394 organizations and their connections to terrorist events in 65 countries. This network is available in `SNACpack` and is called `baad_net`. To review documentation on the network, use `?baad_net`.

For the `baad_net` network, do the following:  

1. Plot the network using the `gplot()` function.
2. Calculate the density of the network.
3. Calculate the degree centrality scores for each set of nodes using the `rowSums()` and `colSums()` functions.  
4. Calculate the mean degree centrality scores.
5. Calculate the standardized degree centrality scores for each set of nodes.  
6. Calculate the mean standardized degree centrality score.  
7. Plot the network using the standardized degree centrality scores (be sure to use the `vertex_rescale()` function to aid with rescaling). 

<br>

## Part II: A Kidnapping Network

For this part of the lab, you will use a network created from the Philippine Kidnappings Data, which is a collection of relationships on the Abu Sayyaf Group (ASG), a violent non-state actor operating in the Southern Philippines. In particular, this data is related to the Salafist movement that was founded by Aburajak Janjalani, a native terrorist of the Southern Philippines in 1991. ASG is active in kidnapping and other kinds of terrorist attacks. The object is a two-mode network, with 246 kidnappers and the 105 terrorist events they attended. This network is available in `SNACpack` and is called `philippine_kidnappings_net`. To review documentation on the network, use `?philippine_kidnappings_net`.

For the `philippine_kidnappings_net` network, repeat steps 1 through 7 from **Part I**.

<br>

## Part III: Your Network

For this part of the lab, I would like you to construct a bipartite network. Think about a type of relationship that is interesting, important, etc., and what it connects. It can be a real example from your life, something fictitious, anything really. The *only* restriction is that it should have <u>at least</u> 25 nodes total (e.g., you could have 15 nodes in the first mode and 10 nodes in the second mode). We will be using this network in the next lab, so please be thoughtful in putting your network together.

After creating your bipartite network create an adjacency matrix of the network using the `matrix()` function then create an object of class `network`. 

Then, repeat steps 1 through 7 from **Part I**.

<br>

## Part IV: Analytical Briefing

Pretend you are presenting your analysis for either **Part I** or **Part II** to a supervisor or investigative team. Your goal is not simply to report numerical results, but to explain what the results reveal about the structure of the network and why the results matter. 

Your briefing should address the following topics:

  * Network Structure
    * Describe the overall structure of the network. How are individuals and locations connected?
    * Can you distinguish between the two types of nodes? What characteristics of the visualization make this possible?
    * Based on your analysis, how would you characterize the organization of the network? Does it appear concentrated around a few nodes, or are connections spread across many nodes?
  * Connectivity
    * Interpret the network density. What does this value represent in the context of the network you are presenting?
    * Would you describe this as a relatively dense or sparse network? Justify your conclusion using both the density statistic and the network visualization.
    * Interpret the mean centrality scores for the two node sets. What do these averages suggest about the typical level of connectivity each set of nodes in the network?
  * Central Actors and Locations
    * Identify the most central node in the network (from either node set). What does this node's position suggest about their role in the network?
    * How does the visualization with node sizes scaled by centrality reinforce or change your interpretation of the numerical results?
  * Implications
    * Assume you are an analyst investigating this network. Based on your analysis, what investigative or intervention strategy would you recommend? Explain how the network structure, density, and centrality findings informed your recommendation.

<br>

____

<br>

# How to Submit

Download the [template for this lab](../labs/templates/lab-05-LastName.zip?raw=true) prior to beginning the lab. 

<br>

### Knitting to HTML

When you have completed your assignment using the template, click the "Knit" button to render your `.RMD` file into a `.HTML` report.

<br>

### Special Instructions

Upload your `.RMD`, `.HTML`, and `.MP4` files to the appropriate link for this assignment on the Canvas page for this course.

<br>

### Before You Submit

Remember to ensure the following before submitting your assignment.

  * Name your files using this format: **Lab-##-LastName.rmd**, **Lab-##-LastName.html**, **Lab-##-LastName.mp4**
  * Show both the solution for your code and write out your answers in the body text 
  * Verify that both files open correctly and that your video includes clear audio narration

See [Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml) for examples of common conventions.

<br>
<br>

### Common Knitting Issues

`.RMD` files are knit into `.HTML` and other formats procedural, or line-by-line.

* An error in code when knitting will halt the process; error messages will tell you the specific line with the error
* Certain functions, like `install.packages()` or `setwd()`, are bound to cause errors in knitting 
* Altering a dataset or variable in one chunk will affect its use in all later chunks
* If an object is "not found", make sure it was created or loaded with `library()` in a previous chunk

**If All Else Fails:** If you cannot determine and fix the errors in a code chunk that's preventing you from knitting your document, add `eval = FALSE` inside the brackets of `{r}` at the beginning of a chunk to ensure that R does not attempt to evaluate it, that is: `{r eval = FALSE}`. This will prevent an erroneous chunk of code from halting the knitting process.  