---
title: "Lab 04 - Closeness/Betweenness Centrality - INSTRUCTIONS"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set ( echo = TRUE )
```

# Introduction

The purpose of this lab is to familiarize yourself with calculating closeness centrality and betweenness centrality scores as well as centralization scores for undirected and directed networks in *R*. Please review the following materials before beginning the lab:

  + [Social Network Analysis for Crime Analysts](https://jacobtnyoung.github.io/snaca-textbook/index.html) textbook chapters:
    + [Closeness Centrality](https://jacobtnyoung.github.io/snaca-textbook/snaca-centrality-closeness.html) 
    + [Betweeness Centrality](https://jacobtnyoung.github.io/snaca-textbook/snaca-centrality-betweenness.html)

  + [Social Network Analysis for Crime Analysts using R](https://jacobtnyoung.github.io/snaca-r/index.html) textbook tutorials:
    + [Closeness Centrality and Centralization](https://jacobtnyoung.github.io/snaca-r/snaca-r-closeness-centrality.html)
    + [Betweenness Centrality and Centralization](https://jacobtnyoung.github.io/snaca-r/snaca-r-betweenness-centrality.html)

In Parts I and II of this lab we will revisit the networks we used in [Lab 3 - Degree Centrality and Centralization](../labs/lab-03-instructions.html). In Part III, you will use the two networks you created from [Lab 1](../labs/lab-01-instructions.html) and [Lab 2](../labs/lab-02-instructions.html). Part IV, gives instructions for your *Analytical Briefing*.

::: {.callout-note title="Network and Matrix Objects"}
*Note* in this lab you will work with objects from the `SNACpack` package. All networks in the `SNACpack` package are of class `network`. This means that to use functions for objects of class `matrix` (such as `dim()` or `sum()`), you need to first coerce the object to a `matrix` object using `as.matrix`. For example: `my_matrix <- as.matrix( my_network )`. Keep this in mind as you work through this lab.
:::

<br>

## Part I: Working with an Undirected Network

For this part of the lab, you will again use data from [Margaret R. Weeks, Scott Clair, Stephen P. Borgatti, Kim Radda & Jean J. Schensul's analysis](https://link.springer.com/article/10.1023/A:1015457400897) of drug users in Hartford, Connecticut. This network is available in `SNACpack` as an object of class `network` and is labeled `drug_net`. To review documentation on the network, use this command: `?drug_net`.

For the `drug_net` network, do the following:  

  1. Calculate the degree, closeness, and betweenness centrality scores for each actor. Feel free to use the `degree()`, `closeness()`, and `betweenness()` functions from the `sna` package.
  2. Calculate and report the standardized degree, closeness, and betweenness centrality scores for each actor.
  3. Calculate the mean closeness centrality score and the mean betweenness centrality score.
  4. Calculate the graph centralization scores for degree, closeness, and betweenness centrality using the `centralization` function in the `sna` package.  
  5. Plot the network three times using the `gplot()` function where each plot sizes the nodes by the centrality score (i.e., a plot for degree centrality, a plot for closeness centrality, and a plot for betweenness centrality).

<br>

## Part II: Working with a Directed Network

For this part of the lab, you will again use data from [Mangia Natarajan's study](https://link.springer.com/article/10.1007/s10940-006-9007-x) heroin trafficking organization in New York City. This network is available in `SNACpack` and is called `heroin_dealing_net`. To review documentation on the network, use this command: `?heroin_dealing_net`. 
  
<br>

For the `heroin_dealing_net` network, do the following:  

  1. Calculate the indegree, outdegree, closeness, and betweenness centrality scores for each actor. Feel free to use the `degree()`, `closeness()`, and `betweenness()` functions from the `sna` package.
  2. Calculate and report the standardized indegree, outdegree, closeness, and betweenness centrality scores for each actor.
  3. Calculate the mean closeness centrality score and the mean betweenness centrality score.
  4. Calculate the graph centralization scores for indegree, outdegree, closeness, and betweenness centrality using the `centralization` function in the `sna` package.  
  5. Plot the network four times using the `gplot()` function where each plot sizes the nodes by the centrality score (i.e., a plot for indegree centrality, a plot for outdegree centrality, a plot for closeness centrality, and a plot for betweenness centrality).

<br>

## Part III: Your Networks

Pick **one** of the networks you created in [Lab 1](../labs/lab-01-instructions.html) and [Lab 2](../labs/lab-02-instructions.html), and do the following:

  * If the network is *undirected*, repeat the steps in Part I.  
  
  * If the network is *directed*, repeat the steps in Part II.

<br>

## Part IV: Analytical Briefing

Pretend you are presenting your analysis for **Part II** to a supervisor or investigative team. Your goal is not simply to report numerical results, but to explain what the results reveal about the structure of the `heroin_dealing_net` network and why the results matter. 

Your briefing should address the following topics:

  * Prediction
    * What types of actors would you expect to have high closeness centrality scores? 
    * What types of actors would you expect to have high betweenness centrality scores?
    * How might an actor with high closeness but low betweenness differ from an actor with high scores on both measures?
    * For *closeness*, what would a completely centralized network mean in this setting? What about a completely decentralized network? What about for *betweenness*?

  * Closeness and Betweenness Centrality
    * Discuss the actor(s) with the highest closeness centrality scores and explain what their positions suggest about their role(s) in the network.
    * Discuss the actor(s) with the highest betweenness centrality scores and explain what their position suggests about their role(s) in the network.
    * Compare the actors identified by the two measures. Do the same individuals emerge as the most central? If not, what does this suggest about the different aspects of network structure captured by closeness and betweenness centrality?

  * Centralization
    * Interpret the closeness and betweenness graph centralization scores.
    * What do the closeness and betweenness centralization scores reveal about this network?
    * Are the closeness and betweenness centralization scores similar or different? What does this tell us about the overall structure of the network? Use both the numerical scores and the visualizations to support your conclusions.

  * Implications
    * Assume you are an analyst assigned to investigate heroin trafficking. Based on your analysis, what investigative or intervention strategy would you recommend?
    * Which actors or positions in the network would you prioritize? 
    * Would your recommendations differ depending on whether your goal is to quickly disseminate information through the network or to disrupt communication between different parts of the network? Explain how your closeness and betweenness centrality findings informed your recommendation.

<br>

____

<br>

# How to Submit

Download the [template for this lab](../labs/templates/lab-04-LastName.zip?raw=true) prior to beginning the lab. 

<br>

### Knitting to HTML

When you have completed your assignment using the template, click the "Knit" button to render your `.RMD` file into a `.HTML` report.

<br>

### Special Instructions

Upload your `.RMD`, `.HTML`, and `.MP4` files to the appropriate link for this assignment on the Canvas page for this course.

<br>

### Before You Submit

Remember to ensure the following before submitting your assignment.

  * Name your files using this format: **Lab-##-LastName.rmd**, **Lab-##-LastName.html**, **Lab-##-LastName.mp4**
  * Show both the solution for your code and write out your answers in the body text 
  * Verify that both files open correctly and that your video includes clear audio narration

See [Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml) for examples of common conventions.

<br>
<br>

### Common Knitting Issues

`.RMD` files are knit into `.HTML` and other formats procedural, or line-by-line.

* An error in code when knitting will halt the process; error messages will tell you the specific line with the error
* Certain functions, like `install.packages()` or `setwd()`, are bound to cause errors in knitting 
* Altering a dataset or variable in one chunk will affect its use in all later chunks
* If an object is "not found", make sure it was created or loaded with `library()` in a previous chunk

**If All Else Fails:** If you cannot determine and fix the errors in a code chunk that's preventing you from knitting your document, add `eval = FALSE` inside the brackets of `{r}` at the beginning of a chunk to ensure that R does not attempt to evaluate it, that is: `{r eval = FALSE}`. This will prevent an erroneous chunk of code from halting the knitting process.  