---
title: "Lab 02 - Network Visualization - INSTRUCTIONS"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE )
```


# Introduction

The purpose of this lab is to familiarize yourself with how networks are created and visualized in *R*.  

<br>

In [Lab 1](../labs/lab-01-instructions.html), you created two networks. 
I would like you to continue working with those networks for *this* lab. 
Please review the [Working with Networks in R](https://jacobtnyoung.github.io/snaca-r/snaca-r-network-data.html), [Basics of Network Visualization](https://jacobtnyoung.github.io/snaca-r/snaca-r-visualization.html), and [Network Description in R](https://jacobtnyoung.github.io/snaca-r/snaca-r-net-description.html) tutorials prior to beginning this lab. 
You will also discuss the descriptive properties of your network. So, be sure to review the [Network Description](https://jacobtnyoung.github.io/snaca-textbook/snaca-net-description.html) chapter of the textbook as you go through that part of the lab.

Two **IMPORTANT** points:  

  + If you created a bipartite (i.e., two or more node sets) network in [Lab 1](../labs/lab-01-instructions.html) for either network, you will need to restructure the network to be unipartite for this assignment. But, this is a simple task! All you have to do is figure out which node set you want to connect and create direct connections between them. For example, if Jon and Julio both attended a [Wu-Tang Clan](https://en.wikipedia.org/wiki/Wu-Tang_Clan) concert, then the bipartite graph is: Jon-Event-Julio. That is, Jon and Julio are connected by the event. To make this unipartite, just remove the event such that you simply have: Jon-Julio.   
  
  + If you created a multiplex network (i.e., a network with multiple edge sets) in [Lab 1](../labs/lab-01-instructions.html) for either network, you will need to make your multiplex network a simplex network for this assignment. You could do this in a few ways. You could select a single set of edges and discard the others. For example, if you had a network where individuals were connected by either friendship or advice seeking, you could select just the friendship ties. Another way is to keep both sets of ties and just treat them as the same thing.    
  
  + If you review the instructions below and you feel like your network is not appropriate for the assignment and need to create a different example...that is fine! We will use these networks throughout the course, so I want to make sure you have something you can work with consistently.  

Make sense? If you have questions before you begin, just post an [issue](https://github.com/Watts-College/crj-507-fall-2025/issues/new) to the course help page.

<br>

For *each* network you created, do the following:  

1. Create an adjacency matrix of the network using the `matrix()` function.
1. Create an object of class `network`. 
1. Plot the network using the `gplot()` function. Modify the plot using at least three arguments in the `gplot()` function.  
1. Calculate the density of the network.

<br>

## Analytical Briefing

In your briefing, address the following for each of your networks:  

  - Introduce your network, briefly describe it and explain what the nodes and ties represent
  - Discuss your visualization, focusing on how your modifications to the plots improve the interpretability of the network
  - Interpret the density and explain what this measure tells you about the overall structure of the network
  - Discuss what insights an analyst might gain from your analysis
  - Compare the two networks focusing your attention on the similarities and differences you observe in your analysis

### Expectations

Your briefing should demonstrate your understanding of network visualization and descriptive network measures. 
Focus on explaining what the visualizations and statistics reveal about the networks rather than simply reporting numerical values or reading answers from your written assignment.

____

<br>

# How to Submit

Download the [template for this lab](../labs/templates/lab-02-LastName.zip?raw=true) prior to beginning the lab. 

<br>

### Knitting to HTML

When you have completed your assignment using the template, click the "Knit" button to render your `.RMD` file into a `.HTML` report.

<br>

### Special Instructions

Upload your `.RMD`, `.HTML`, and `.MP4` files to the appropriate link for this assignment on the Canvas page for this course.

<br>

### Before You Submit

Remember to ensure the following before submitting your assignment.

  * Name your files using this format: **Lab-##-LastName.rmd**, **Lab-##-LastName.html**, **Lab-##-LastName.mp4**
  * Show both the solution for your code and write out your answers in the body text 
  * Verify that both files open correctly and that your video includes clear audio narration

See [Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml) for examples of common conventions.

<br>
<br>

### Common Knitting Issues

`.RMD` files are knit into `.HTML` and other formats procedural, or line-by-line.

* An error in code when knitting will halt the process; error messages will tell you the specific line with the error
* Certain functions, like `install.packages()` or `setwd()`, are bound to cause errors in knitting 
* Altering a dataset or variable in one chunk will affect its use in all later chunks
* If an object is "not found", make sure it was created or loaded with `library()` in a previous chunk

**If All Else Fails:** If you cannot determine and fix the errors in a code chunk that's preventing you from knitting your document, add `eval = FALSE` inside the brackets of `{r}` at the beginning of a chunk to ensure that R does not attempt to evaluate it, that is: `{r eval = FALSE}`. This will prevent an erroneous chunk of code from halting the knitting process.  