---
title: "Lab 06 - Projection of Bipartite Graphs - INSTRUCTIONS"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE )
```

# Introduction

The purpose of this lab is to familiarize yourself with projecting bipartite graphs to unipartite graphs in *R*. 
Prior to beginning this lab, please review the [Projection](https://jacobtnyoung.github.io/snaca-textbook/snaca-projection.html) chapter of the [Social Network Analysis for Crime Analysts](https://jacobtnyoung.github.io/snaca-textbook/index.html) textbook as well as the [Projection & Weighted Graphs](https://jacobtnyoung.github.io/snaca-r/snaca-r-projection.html) tutorial in the [Social Network Analysis for Crime Analysts using R](https://jacobtnyoung.github.io/snaca-r/index.html) textbook.

In Parts I and II of this lab, we will revisit the networks we used in [Lab 5](../labs/lab-05-instructions.html), and in Part III, you will use the bipartite network you created in [Lab 5](../labs/lab-05-instructions.html). 
Part IV, gives instructions for your *Analytical Briefing*.

::: {.callout-note title="Network and Matrix Objects"}
*Note* that the objects, and all networks in the `SNACpack` package, are of class `network`. This means that to use functions for objects of class `matrix` (such as `dim()` or `sum()`), you need to first coerce the object to a `matrix` object using `as.matrix`. For example: `my_matrix <- as.matrix( my_network )`.
:::

<br>

## Part I: A Terrorism Network

For this part of the lab, you will again use the network of terrorist organizations analyzed by [Victor Asal and R. Karl Rethemeyer' study](https://www.journals.uchicago.edu/doi/10.1017/S0022381608080419). This network is available in `SNACpack` and is called `baad_net`. To review documentation on the network, use `?baad_net`.

### Bipartite Graph and Projections

For the `baad_net` network, do the following:  

1. Create an object of class `matrix` from the `baad_net` network. Use the `as.sociomatrix()` function in the `network` package to do so. ( **NOTE: DO NOT PRINT OUT THE MATRIX**).
2. Create the unipartite graph that represents the *person* matrix.
3. Create the unipartite graph that represents the *group* matrix.
4. Plot all three networks. Use the `edge_rescale()` and `edge_shade()` functions in the `SNACpack` package to use the edge weights in the plots for each projected graph.

### *Person* Matrix Projection

For the *person* matrix you created in step 2, do the following:

5. Create an object of class `network` using the `as.network()` function. Pay attention to the correct usage of the `directed=` argument.
6. Calculate the degree, closeness, and betweenness centrality scores for each actor. Feel free to use the `degree()`, `closeness()`, and `betweenness()` functions from the `sna` package.
7. Calculate the mean  degree, closeness, and betweenness centrality scores. 
8. Calculate the graph centralization scores for degree, closeness, and betweenness centrality.  
9. Plot the network three times using the `gplot()` function where each plot sizes the nodes by the centrality score (i.e., a plot for degree centrality, a plot for closeness centrality, and a plot for betweenness centrality). Be sure to use the `vertex_rescale()` functiont to aid with the visualization.

<br>

## Part II: A Kidnapping Network

For this part of the lab, you will again use the network created from the Philippine Kidnappings Data. This network is available in `SNACpack` and is called `philippine_kidnappings_net`. To review documentation on the network, use `?philippine_kidnappings_net`.

For the `philippine_kidnappings_net` network, repeat steps 1-4 from *Part I*.
For the *person* matrix you created in step 2, repeat steps 5-9 from *Part I*.

<br>

## Part III: Your Network

For this part of the lab, I would like you to use the bipartite network you created in [Lab 5](../labs/lab-05-instructions.html). 
For the bipartite network you created, repeat steps 1-4 from *Part I*.
For the *person* matrix you created in step 2, repeat steps 5-9 from *Part I*.

<br>

## Part IV: Analytical Briefing

Pretend you are presenting your analysis for either **Part I** or **Part II** to a supervisor or investigative team. Your goal is not simply to report numerical results, but to explain what the results reveal about the structure of the network and why the results matter. 

Your briefing should address the following topics:

  * Projected Network Structure
    * Explain what the ties in the projected person network represent. How does this network differ from the original bipartite network?
    * How does visualizing edge weights help interpret the structure of the projected network? What additional information do the edge weights provide?
    * Based on your analysis, how would you characterize the overall structure of the projected network?
  * Centrality
    * Discuss the individuals with the highest degree, closeness, and betweenness centrality scores. What do their positions suggest about their roles in the network?
    * Compare the actors identified by each centrality measure. Did the same individuals emerge as the most central? If not, what does this suggest about the different aspects of network structure captured by degree, closeness, and betweenness centrality?
    * Interpret the mean degree, closeness, and betweenness centrality scores. What do these averages suggest about the typical level of connectivity and influence within the network?
  * Centralization
    * Interpret the degree, closeness, and betweenness graph centralization scores.
    * What do these scores reveal about the distribution of centrality throughout the network?
    * Are the three centralization scores similar or different? What do they suggest about whether the network is organized around a few key individuals or is more evenly connected? Use both the numerical scores and the visualizations to support your conclusions.
  * Implications
    * Assume you are an analyst advising authorities seeking to intervene with this network. Based on your analysis, what investigative or intervention strategy would you recommend? 
    * Which individuals would you prioritize, and would your recommendations differ depending on whether your objective is to identify the most well-connected individuals, those who can quickly spread information, or those who serve as brokers between different parts of the network? Explain how your centrality and centralization findings informed your recommendation.

<br>

____

<br>

# How to Submit

Download the [template for this lab](../labs/templates/lab-06-LastName.zip?raw=true) prior to beginning the lab. 

<br>

### Knitting to HTML

When you have completed your assignment using the template, click the "Knit" button to render your `.RMD` file into a `.HTML` report.

<br>

### Special Instructions

Upload your `.RMD`, `.HTML`, and `.MP4` files to the appropriate link for this assignment on the Canvas page for this course.

<br>

### Before You Submit

Remember to ensure the following before submitting your assignment.

  * Name your files using this format: **Lab-##-LastName.rmd**, **Lab-##-LastName.html**, **Lab-##-LastName.mp4**
  * Show both the solution for your code and write out your answers in the body text 
  * Verify that both files open correctly and that your video includes clear audio narration

See [Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml) for examples of common conventions.

<br>
<br>

### Common Knitting Issues

`.RMD` files are knit into `.HTML` and other formats procedural, or line-by-line.

* An error in code when knitting will halt the process; error messages will tell you the specific line with the error
* Certain functions, like `install.packages()` or `setwd()`, are bound to cause errors in knitting 
* Altering a dataset or variable in one chunk will affect its use in all later chunks
* If an object is "not found", make sure it was created or loaded with `library()` in a previous chunk

**If All Else Fails:** If you cannot determine and fix the errors in a code chunk that's preventing you from knitting your document, add `eval = FALSE` inside the brackets of `{r}` at the beginning of a chunk to ensure that R does not attempt to evaluate it, that is: `{r eval = FALSE}`. This will prevent an erroneous chunk of code from halting the knitting process.  